# Generated by Django 4.2.5 on 2023-10-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_labdevice_calibration_date_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle',
            field=models.ManyToManyField(blank=True, to='company.vehicle'),
        ),
    ]
