# Generated by Django 4.2.5 on 2023-10-06 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('accounts', '0002_alter_user_company_alter_user_vehicles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='vehicles',
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='company.vehicle',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='user',
                to='company.company',
            ),
        ),
    ]
