# Generated by Django 4.2.5 on 2023-10-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_labdevice_calibration_date_and_more'),
        ('accounts', '0002_remove_user_vehicle_user_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vehicle',
            field=models.ManyToManyField(
                blank=True, null=True, to='company.vehicle'
            ),
        ),
    ]
