# Generated by Django 4.2.5 on 2023-10-29 16:25

from django.db import migrations, models
import django.db.models.deletion
import qlab.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=qlab.apps.core.models.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ('user.create', 'KULLANICI OLUŞTUR'),
                        ('user.view', 'KULLANICI GÖRÜNTÜLE'),
                        ('user.update', 'KULLANICI GÜNCELLE'),
                        ('user.destroy', 'KULLANICI SİL'),
                    ],
                    max_length=32,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=32)),
                (
                    'permissions',
                    qlab.apps.core.models.ChoiceArrayField(
                        base_field=models.CharField(
                            choices=[
                                ('user.create', 'KULLANICI OLUŞTUR'),
                                ('user.view', 'KULLANICI GÖRÜNTÜLE'),
                                ('user.update', 'KULLANICI GÜNCELLE'),
                                ('user.destroy', 'KULLANICI SİL'),
                            ],
                            max_length=32,
                        ),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
            ],
            options={
                'unique_together': {('name',)},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='roles',
                to='accounts.role',
            ),
        ),
    ]
