# Generated by Django 4.2.5 on 2023-10-15 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_labdevice_alter_qualitymethod_general_information_and_more'),
        ('accounts', '0003_remove_user_vehicles_user_vehicle_alter_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.labdevice'),
        ),
    ]
