# Generated by Django 4.2.5 on 2023-10-18 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_labdevice_calibration_date_and_more'),
        ('accounts', '0003_alter_user_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='company.vehicle',
            ),
        ),
    ]
