# Generated by Django 4.2.5 on 2023-10-30 13:23

from django.db import migrations, models
import qlab.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_permissions_role_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=qlab.apps.core.models.ChoiceArrayField(base_field=models.CharField(choices=[('user.create', 'KULLANICI OLUŞTUR'), ('user.view', 'KULLANICI GÖRÜNTÜLE'), ('user.update', 'KULLANICI GÜNCELLE'), ('user.destroy', 'KULLANICI SİL'), ('group.create', 'GRUP OLUŞTUR'), ('group.view', 'GRUP GÖRÜNTÜLE'), ('group.update', 'GRUP GÜNCELLE'), ('group.destroy', 'GRUP SİL'), ('vehicle.create', 'ARAÇ OLUŞTUR'), ('vehicle.view', 'ARAÇ GÖRÜNTÜLE'), ('vehicle.update', 'ARAÇ GÜNCELLE'), ('vehicle.destroy', 'ARAÇ SİL'), ('company.create', 'FİRMA OLUŞTUR'), ('company.view', 'FİRMA GÖRÜNTÜLE'), ('company.update', 'FİRMA GÜNCELLE'), ('company.destroy', 'FİRMA SİL'), ('method.create', 'METOT OLUŞTUR'), ('method.view', 'METOT GÖRÜNTÜLE'), ('method.update', 'METOT GÜNCELLE'), ('method.destroy', 'METOT SİL'), ('parameter.create', 'PARAMETRE OLUŞTUR'), ('parameter.view', 'PARAMETRE GÖRÜNTÜLE'), ('parameter.update', 'PARAMETRE GÜNCELLE'), ('parameter.destroy', 'PARAMETRE SİL'), ('device.create', 'CİHAZ OLUŞTUR'), ('device.view', 'CİHAZ GÖRÜNTÜLE'), ('device.update', 'CİHAZ GÜNCELLE'), ('device.destroy', 'CİHAZ SİL'), ('draft.create', 'TASLAK OLUŞTUR'), ('draft.view', 'TASLAK GÖRÜNTÜLE'), ('draft.update', 'TASLAK GÜNCELLE'), ('draft.destroy', 'TASLAK SİL'), ('proposal_create', 'TEKLİF OLUŞTUR'), ('proposal_update', 'TEKLİF GÜNCELLE'), ('proposal_view', 'TEKLİF GÖRÜNTÜLE'), ('statistics.view', 'İSTATİSTİK GÖRÜNTÜLE'), ('note.create', 'NOT OLUŞTUR'), ('note.view', 'NOT GÖRÜNTÜLE'), ('note.update', 'NOT GÜNCELLE'), ('note.destroy', 'NOT SİL')], max_length=32), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='permissions',
            field=qlab.apps.core.models.ChoiceArrayField(base_field=models.CharField(choices=[('user.create', 'KULLANICI OLUŞTUR'), ('user.view', 'KULLANICI GÖRÜNTÜLE'), ('user.update', 'KULLANICI GÜNCELLE'), ('user.destroy', 'KULLANICI SİL'), ('group.create', 'GRUP OLUŞTUR'), ('group.view', 'GRUP GÖRÜNTÜLE'), ('group.update', 'GRUP GÜNCELLE'), ('group.destroy', 'GRUP SİL'), ('vehicle.create', 'ARAÇ OLUŞTUR'), ('vehicle.view', 'ARAÇ GÖRÜNTÜLE'), ('vehicle.update', 'ARAÇ GÜNCELLE'), ('vehicle.destroy', 'ARAÇ SİL'), ('company.create', 'FİRMA OLUŞTUR'), ('company.view', 'FİRMA GÖRÜNTÜLE'), ('company.update', 'FİRMA GÜNCELLE'), ('company.destroy', 'FİRMA SİL'), ('method.create', 'METOT OLUŞTUR'), ('method.view', 'METOT GÖRÜNTÜLE'), ('method.update', 'METOT GÜNCELLE'), ('method.destroy', 'METOT SİL'), ('parameter.create', 'PARAMETRE OLUŞTUR'), ('parameter.view', 'PARAMETRE GÖRÜNTÜLE'), ('parameter.update', 'PARAMETRE GÜNCELLE'), ('parameter.destroy', 'PARAMETRE SİL'), ('device.create', 'CİHAZ OLUŞTUR'), ('device.view', 'CİHAZ GÖRÜNTÜLE'), ('device.update', 'CİHAZ GÜNCELLE'), ('device.destroy', 'CİHAZ SİL'), ('draft.create', 'TASLAK OLUŞTUR'), ('draft.view', 'TASLAK GÖRÜNTÜLE'), ('draft.update', 'TASLAK GÜNCELLE'), ('draft.destroy', 'TASLAK SİL'), ('proposal_create', 'TEKLİF OLUŞTUR'), ('proposal_update', 'TEKLİF GÜNCELLE'), ('proposal_view', 'TEKLİF GÖRÜNTÜLE'), ('statistics.view', 'İSTATİSTİK GÖRÜNTÜLE'), ('note.create', 'NOT OLUŞTUR'), ('note.view', 'NOT GÖRÜNTÜLE'), ('note.update', 'NOT GÜNCELLE'), ('note.destroy', 'NOT SİL')], max_length=32), blank=True, default=list, size=None),
        ),
    ]
