# Generated by Django 4.2.5 on 2023-10-19 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_labdevice_calibration_date_and_more'),
        ('accounts', '0004_remove_user_vehicle_user_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vehicle',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='user',
                to='company.vehicle',
            ),
        ),
    ]
