# Generated by Django 4.2.5 on 2023-11-12 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import qlab.apps.core.utils.set_path


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_role_permissions_alter_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'detail',
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    'criminal_record',
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=qlab.apps.core.utils.set_path.SetPathAndRename(
                            'profile/criminal_record/'
                        ),
                    ),
                ),
                (
                    'military_certificate',
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=qlab.apps.core.utils.set_path.SetPathAndRename(
                            'profile/military_document/'
                        ),
                    ),
                ),
                (
                    'blood_group_certificate',
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=qlab.apps.core.utils.set_path.SetPathAndRename(
                            'profile/blood_group/'
                        ),
                    ),
                ),
                (
                    'driver_certificate',
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=qlab.apps.core.utils.set_path.SetPathAndRename(
                            'profile/driver_certificate/'
                        ),
                    ),
                ),
                (
                    'emission_certificate',
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=qlab.apps.core.utils.set_path.SetPathAndRename(
                            'profile/emission_certificate/'
                        ),
                    ),
                ),
                (
                    'height_certificate',
                    models.FileField(
                        blank=True,
                        help_text='Yüksekte çalışma belgesi',
                        null=True,
                        upload_to=qlab.apps.core.utils.set_path.SetPathAndRename(
                            'profile/height_certificate/'
                        ),
                    ),
                ),
                (
                    'graduate_certificate',
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=qlab.apps.core.utils.set_path.SetPathAndRename(
                            'profile/graduate_certificate/'
                        ),
                    ),
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
