# Generated by Django 4.2.7 on 2023-11-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_role_permissions_alter_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
