# Generated by Django 4.2.7 on 2023-12-02 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('accounts', '0009_alter_role_permissions_alter_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant.organization'),
        ),
    ]
