# Generated by Django 4.2.5 on 2023-10-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='medium',
            field=models.CharField(
                choices=[
                    ('sms', 'Sms'),
                    ('email', 'Email'),
                    ('notification', 'Notification'),
                ],
                default='email',
                max_length=16,
                verbose_name='Kanal',
            ),
        ),
    ]
