# Generated by Django 4.2.5 on 2023-10-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_notification_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='medium',
            field=models.CharField(
                choices=[
                    ('sms', 'Sms'),
                    ('email', 'Email'),
                    ('notification', 'Notification'),
                ],
                default='notification',
                max_length=16,
                verbose_name='Kanal',
            ),
        ),
    ]
