# Generated by Django 4.2.5 on 2023-10-16 19:25

from django.db import migrations, models
import phonenumber_field.modelfields
import qlab.apps.core.utils.set_path


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('tax_number', models.CharField(max_length=10)),
                ('authorized_person', models.CharField(max_length=50)),
                ('contact_info', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, null=True, region=None)),
                ('contact_info_mail', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('serial_number', models.CharField(max_length=128)),
                ('calibration_date', models.DateTimeField()),
                ('calibration_period', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='QualityMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_name', models.CharField(max_length=64)),
                ('measurement_number', models.CharField(max_length=64)),
                ('general_information', models.CharField(blank=True, max_length=64, null=True)),
                ('price', models.IntegerField(default=0)),
                ('general_file', models.FileField(blank=True, null=True, upload_to=qlab.apps.core.utils.set_path.SetPathAndRename('method/'))),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=16)),
                ('brand', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=64)),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('insurance_date', models.DateField()),
                ('maintenance_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
