# Generated by Django 4.2.5 on 2023-10-23 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'company',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='company.company',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ProposalDraft',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=128)),
                ('preface', models.TextField()),
                ('terms', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProposalMethodParameters',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('count', models.SmallIntegerField()),
                (
                    'parameter',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='company.methodparameters',
                    ),
                ),
                (
                    'proposal',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='company.proposal',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='proposal',
            name='draft',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='company.proposaldraft',
            ),
        ),
        migrations.AddField(
            model_name='proposal',
            name='parameters',
            field=models.ManyToManyField(
                through='company.ProposalMethodParameters',
                to='company.methodparameters',
            ),
        ),
    ]
