# Generated by Django 4.2.7 on 2023-11-20 15:38

from django.db import migrations, models
import django.db.models.deletion
import qlab.apps.core.utils.set_path


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalLogo',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=128)),
                (
                    'left_logo',
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=qlab.apps.core.utils.set_path.SetPathAndRename(
                            'proposal/logo/'
                        ),
                    ),
                ),
                (
                    'right_logo',
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=qlab.apps.core.utils.set_path.SetPathAndRename(
                            'proposal/logo/'
                        ),
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='proposal',
            name='company',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='company.company',
            ),
        ),
        migrations.AddField(
            model_name='proposal',
            name='logo',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='company.proposallogo',
            ),
        ),
    ]
