# Generated by Django 4.2.7 on 2023-12-03 17:57

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact_info',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=16, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_info_mail',
            field=models.EmailField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
