# Generated by Django 4.2.5 on 2023-10-10 13:24

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact_info',
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                db_index=True,
                max_length=128,
                null=True,
                region=None,
            ),
        ),
    ]
