# Generated by Django 4.2.5 on 2023-10-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'company',
            '0002_proposal_proposaldraft_proposalmethodparameters_and_more',
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='parameters',
        ),
        migrations.AddField(
            model_name='proposal',
            name='status',
            field=models.IntegerField(
                choices=[
                    (0, 'Teklif Gönderildi'),
                    (1, 'Teklif Onaylandı'),
                    (2, 'Teklif Kabul Edilmedi'),
                    (3, 'İşlem İptal Edildi'),
                    (4, 'İşlem Kabul Edildi'),
                ],
                default=0,
            ),
        ),
    ]
