# Generated by Django 4.2.5 on 2023-10-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_qualitymethod_company_contact_info_mail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitymethod',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
