# Generated by Django 4.2.5 on 2023-10-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_qualitymethod_company_contact_info_mail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=64, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=128, null=True)),
                ('calibration_date', models.DateTimeField(blank=True, null=True)),
                ('calibration_period', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='qualitymethod',
            name='general_information',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='qualitymethod',
            name='measurement_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='qualitymethod',
            name='measurement_number',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
