# Generated by Django 4.2.5 on 2023-10-18 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0003_labdevice_user_alter_labdevice_calibration_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labdevice',
            name='calibration_date',
        ),
        migrations.RemoveField(
            model_name='labdevice',
            name='calibration_period',
        ),
        migrations.AddField(
            model_name='labdevice',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labdevice',
            name='period',
            field=models.IntegerField(
                help_text='calibration period', null=True
            ),
        ),
        migrations.AddField(
            model_name='labdevice',
            name='start_date',
            field=models.DateField(help_text='calibration date', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='labdevice',
            name='user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
