# Generated by Django 4.2.5 on 2023-10-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_proposal_parameters_proposal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
