# Generated by Django 4.2.7 on 2023-11-23 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import qlab.apps.company.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            'company',
            '0003_organizationinformation_remove_proposal_logo_and_more',
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='organization_info',
        ),
        migrations.AddField(
            model_name='organizationinformation',
            name='bank_branch',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='organizationinformation',
            name='bank_iban',
            field=models.CharField(
                max_length=128,
                null=True,
                validators=[qlab.apps.company.models.validate_iban],
            ),
        ),
        migrations.AddField(
            model_name='organizationinformation',
            name='bank_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='organizationinformation',
            name='bank_no',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='organizationinformation',
            name='user',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='organizationinformation',
            name='address',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='organizationinformation',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='organizationinformation',
            name='owner',
            field=models.CharField(max_length=128),
        ),
    ]
