# Generated by Django 4.2.5 on 2023-10-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_labdevice_calibration_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualitymethod',
            name='general_information',
        ),
        migrations.RemoveField(
            model_name='qualitymethod',
            name='price',
        ),
        migrations.AddField(
            model_name='qualitymethod',
            name='acceptance_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='qualitymethod',
            name='measurement_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='qualitymethod',
            name='measurement_number',
            field=models.CharField(max_length=256),
        ),
    ]
