# Generated by Django 4.2.5 on 2023-10-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_proposal_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalmethodparameters',
            name='method',
            field=models.ManyToManyField(related_name='proposal_parameters', to='company.qualitymethod'),
        ),
    ]
