# Generated by Django 4.2.7 on 2023-11-23 09:40

from django.db import migrations, models
import qlab.apps.core.utils.set_path


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_proposal_organization_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationinformation',
            name='signature',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=qlab.apps.core.utils.set_path.SetPathAndRename(
                    'signature/'
                ),
            ),
        ),
    ]
