# Generated by Django 4.2.5 on 2023-10-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_labdevice_calibration_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualitymethod',
            name='general_information',
        ),
        migrations.RemoveField(
            model_name='qualitymethod',
            name='price',
        ),
        migrations.AddField(
            model_name='qualitymethod',
            name='acceptance_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='qualitymethod',
            name='measurement_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='qualitymethod',
            name='measurement_number',
            field=models.CharField(max_length=256),
        ),
        migrations.CreateModel(
            name='MethodParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('method', models.ManyToManyField(related_name='parameters', to='company.qualitymethod')),
            ],
        ),
    ]
