# Generated by Django 4.2.5 on 2023-10-20 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_remove_qualitymethod_general_information_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.qualitymethod')),
            ],
        ),
    ]
