# Generated by Django 4.2.5 on 2023-10-26 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_proposalmethodparameters_method'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProposalMethodParameters',
        ),
    ]
