# Generated by Django 4.2.7 on 2023-11-24 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0005_alter_organizationinformation_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='advisor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('goal', models.TextField(blank=True, null=True)),
                (
                    'devices',
                    models.ManyToManyField(
                        related_name='work_order', to='company.labdevice'
                    ),
                ),
                (
                    'personal',
                    models.ManyToManyField(
                        related_name='work_order', to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    'proposal',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='work_order',
                        to='company.proposal',
                    ),
                ),
                (
                    'vehicles',
                    models.ManyToManyField(
                        related_name='work_order', to='company.vehicle'
                    ),
                ),
            ],
        ),
    ]
