# Generated by Django 4.2.5 on 2023-10-27 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_remove_proposalmethodparameters_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposalmethodparameters',
            old_name='method_name',
            new_name='methods',
        ),
    ]
