# Generated by Django 4.2.7 on 2023-11-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_advisor_workorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
