# Generated by Django 4.2.5 on 2023-10-26 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_proposalmethodparameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalmethodparameters',
            name='proposal',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='parameters',
                to='company.proposal',
            ),
        ),
    ]
