# Generated by Django 4.2.7 on 2023-11-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_workorder_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companynote',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.IntegerField(
                choices=[
                    (0, 'Teklif Gönderildi'),
                    (1, 'Teklif Onaylandı'),
                    (2, 'Teklif Kabul Edilmedi'),
                    (3, 'İş Emri Oluşturuldu'),
                ],
                default=0,
            ),
        ),
    ]
