# Generated by Django 4.2.7 on 2023-11-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_companynote_notes_alter_proposal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalmethodparameters',
            name='source_code',
            field=models.CharField(blank=True, null=True),
        ),
    ]
