# Generated by Django 4.2.5 on 2023-10-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_proposal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
