# Generated by Django 4.2.5 on 2023-10-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_proposal_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyNote',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('notes', models.JSONField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='proposalmethodparameters',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
