# Generated by Django 4.2.5 on 2023-10-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_companynote_proposalmethodparameters_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalmethodparameters',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
