# Generated by Django 4.2.7 on 2023-11-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_methodparameters_barcode_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact_info',
            field=models.CharField(
                blank=True, db_index=True, max_length=16, null=True
            ),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_info_mail',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
