# Generated by Django 4.2.5 on 2023-11-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_alter_proposalmethodparameters_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('text', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='companynote',
            name='notes',
        ),
        migrations.AddField(
            model_name='companynote',
            name='notes',
            field=models.ManyToManyField(
                related_name='company', to='company.notes'
            ),
        ),
    ]
