# Generated by Django 4.2.7 on 2023-11-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_alter_company_contact_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='barcode_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
