# Generated by Django 4.2.5 on 2023-11-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_notes_remove_companynote_notes_companynote_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companynote',
            name='notes',
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
        migrations.AddField(
            model_name='companynote',
            name='notes',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
