# Generated by Django 4.2.7 on 2023-11-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_methodparameters_current_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methodparameters',
            name='barcode_count',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='methodparameters',
            name='current_barcode',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
