# Generated by Django 4.2.5 on 2023-11-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_remove_companynote_notes_delete_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.IntegerField(choices=[(0, 'Teklif Gönderildi'), (1, 'Teklif Onaylandı'), (2, 'Teklif Kabul Edilmedi')], default=0),
        ),
    ]
