# Generated by Django 4.2.7 on 2023-11-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_alter_methodparameters_barcode_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methodparameters',
            name='barcode_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='methodparameters',
            name='current_barcode',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
